services:
  - type: web
    name: yvix-assignment-portal
    env: python
    buildCommand: pip install -r requirements-render.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true 